apiVersion: v1
kind: Namespace
metadata:
  name: semraninsayfalari
---
apiVersion: v1
kind: Service
metadata:
  name: semraninsayfalari
  namespace: semraninsayfalari
spec:
  ports:
     - port: 80
  selector:
    app: semraninsayfalari
  type: LoadBalancer   
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: semraninsayfalari
  namespace: semraninsayfalari
spec:
  replicas: 1
  selector:
    matchLabels:
      app: semraninsayfalari
  template:
    metadata:
      labels:
        app: semraninsayfalari
    spec:
      containers:
      - name: semraninsayfalari
        image: dockerdepo.azurecr.io/semraydin/semraninsayfalari:#{Build.BuildId}#
        imagePullPolicy: Always
        env:
        - name: VERSION
          value: "v1"
      imagePullSecrets:
      - name: docker-depo-pass-semraninsayfalari
